struct StructA {
  a: vec3f,
}

struct StructB {
  a: vec3f,
}

struct StructC {
  a: vec3f,
}

struct StructD {
  a: vec3f,
}

struct StructE {
  a: vec3f,
}

struct StructF {
  a: vec3f,
}

struct StructG {
  a: vec3f,
}

struct StructH {
  a: vec3f,
}

struct StructI {
  a: vec3f,
}

struct StructJ {
  a: vec3f,
}

struct StructK {
  a: vec3f,
}

fn my_function() -> vec2f {
  return vec4f(1.0, 0.0);
}